### ISSUE TITLE
Character select missing

### ISSUE THREAD

**Issue by rtroberts** [AllynH/destiny_focus#7]
Allyn, really appreciate all the hard work you've put into this! What a useful tool.

For me, the character select box is always empty white, like the following:
![image](https://user-images.githubusercontent.com/8681332/167459165-0889c95b-0211-424e-aca8-9b1a18d224f1.png)

Perhaps because `/auth/get/get_characters` is returning a 500. 

Hopefully I'm not wasting your time with a spurious, temporal issue, but I figured I'd report it anyway.

**Comment by AllynH** [comment]
Hi @rtroberts 

I've been looking through the gunicorn log files and it seems Bungie were returning some strange errors. 
I checked out Bungie Help on Twitter and saw they were doing some maintenance at the time. Bungie's servers do some strange stuff in maintenance mode and there are no real standard errors. 

So I'm hoping this is all related to the maintenance mode but I've added an additional check in the auth flow for this error. Code pushed, it'll be deployed shortly. 

Bungie help Tweet:

https://twitter.com/bungiehelp/status/1523709380859936771?s=21&t=Dtvuh5JkI4alA0o5mF9coA

Can you check back shortly and see if it's resolved?
Maintenance is still running for about 30 minutes.

**Comment by AllynH** [comment]
Code commit:

https://github.com/AllynH/destiny_focus/commit/0520d94a66cf74240a602cc4f21bf08e135662a3

**Comment by rtroberts** [comment]
I can successfully make a request like `https://www.bungie.net/Platform/Destiny2/2/Profile/4611686018436793293/?components=102%2C103%2C200%2C201%2C205%2C300%2C305%2C310`, which if I am reading the code correctly, `/get/get_characters` is using. However, that endpoint is still throwing a 500 error for me, so perhaps it's something else.

**Comment by AllynH** [comment]
Can you check your privacy settings here:

https://www.bungie.net/7/en/User/Account/Privacy

![image](https://user-images.githubusercontent.com/6655221/167502446-ca8a1d9d-d2b4-4a7c-9c71-949209a47e45.jpeg)

**Comment by rtroberts** [comment]
![image](https://user-images.githubusercontent.com/8681332/167503069-b9ce1afe-9011-428e-81e2-dd33f45de6cf.png)

Of course, here it is!

**Comment by rtroberts** [comment]
I could also upload the results of the `Profile` call in a file (it's rather large) if it could be a parsing issue.

**Comment by AllynH** [comment]
> ![image](https://user-images.githubusercontent.com/8681332/167503069-b9ce1afe-9011-428e-81e2-dd33f45de6cf.png)
> 
> 
> 
> Of course, here it is!

You'll need to enable "show my non-equipped inventory". 
I make a call to get your profile information, which is the same API endpoint as your inventory. 

Essentially all character information, including your inventory, is accessed via that endpoint.

**Comment by rtroberts** [comment]
Interesting. I did try turning that on, logging out, hard refreshing, and logging back in - to no effect.

**Comment by AllynH** [comment]
> I could also upload the results of the `Profile` call in a file (it's rather large) if it could be a parsing issue.

Can you try to post this to a private gist and I'll have a look?

https://docs.github.com/en/get-started/writing-on-github/editing-and-sharing-content-with-gists/creating-gists#creating-a-gist

**Comment by rtroberts** [comment]
It's not private but it's only Destiny, I don't mind sharing :)

https://gist.github.com/rtroberts/603931bf2ce518a7b6961d0415b5ed47

**Comment by jtwee** [comment]
I'm having the same issue. Is there anything I can contribute to see what may be consistent with our profiles?

**Comment by AllynH** [comment]
It seems there was a strange issue in the Risen title DestinyRecordDefinition where it doesn't include an icon (displayProperties["icon"]) for that title. 
This was causing a 500 error in my code, as the value is returned to the user. 

https://data.destinysets.com/i/Record:1710217127

This has been fixed now, please try again. 

Cc @jtwee

**Comment by AllynH** [comment]
Commit:

https://github.com/AllynH/destiny_focus/commit/9c30c8713ad09fde9576353f78bb57cf18479177

**Comment by rtroberts** [comment]
Wow, weird. This commit has resolved the issue for me. Thanks for the help, @AllynH!

**Comment by AllynH** [comment]
Delighted to hear that, thanks for logging the issue. @jtwee  also messaged me to say it's working for them. 
Hope you enjoy the app, let me know if there's anything else that needs fixing.
